# workflow name
name: Build & Publish release

# on events
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Package version
        required: true

# workflow tasks
jobs:
  build:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate build files
        uses: psethwick/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'vanity-sniper'
            compress: 'true'
            dest: 'dist'
  publish:
    name: Publish release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/**"
          tag: ${{ inputs.version }}